# docker-compose.yml

version: '3.8'

networks:
  fl-net:
    driver: bridge

services:
  fl-api:
    build: .
    container_name: fl-api-server
    command: python3 scratch/main.py --port 5005
    networks:
      - fl-net
    volumes:
      - .:/app

  ns3-simulation:
    build: .
    container_name: ns3-simulation-runner
    depends_on:
      - fl-api
    networks:
      - fl-net
    environment:
      - FL_API_URL=http://fl-api:5005
    # Keep the container alive and interactive for the shell
    stdin_open: true  # Add this line
    tty: true         # Add this line
    command: >
      bash -c "
        set -e;
        
        echo 'Configuring and building ns-3 simulation in DEBUG mode...';
        # IMPORTANT: Build in debug mode for GDB
        ./ns3 configure --build-profile=debug;
        ./ns3 build;

        while ! curl -s http://fl-api:5005/ping > /dev/null; do
          echo 'Waiting for FL API server...';
          sleep 2;
        done;
        echo 'FL API server is responsive. Starting ns-3 simulation.';
        
        # Run the simulation. If it fails (crashes), start a bash shell.
        ./ns3 run 'simulation_main' || bash;
      "
    volumes:
      - .:/app
      - ./results:/app/results